// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[COMMA-5]
	_ = x[DOT-6]
	_ = x[MINUS-7]
	_ = x[PLUS-8]
	_ = x[SLASH-9]
	_ = x[STAR-10]
	_ = x[SEMICOLON-11]
	_ = x[COLON-12]
	_ = x[QUESTION-13]
	_ = x[BANG-14]
	_ = x[BANG_EQUAL-15]
	_ = x[EQUAL-16]
	_ = x[EQUAL_EQUAL-17]
	_ = x[GREATER-18]
	_ = x[GREATER_EQUAL-19]
	_ = x[LESS-20]
	_ = x[LESS_EQUAL-21]
	_ = x[IDENTIFIER-22]
	_ = x[STRING-23]
	_ = x[NUMBER-24]
	_ = x[VAR-25]
	_ = x[FUN-26]
	_ = x[CLASS-27]
	_ = x[SUPER-28]
	_ = x[THIS-29]
	_ = x[IF-30]
	_ = x[ELSE-31]
	_ = x[WHILE-32]
	_ = x[FOR-33]
	_ = x[OR-34]
	_ = x[AND-35]
	_ = x[ASSERT-36]
	_ = x[PRINT-37]
	_ = x[RETURN-38]
	_ = x[BREAK-39]
	_ = x[CONTINUE-40]
	_ = x[NIL-41]
	_ = x[TRUE-42]
	_ = x[FALSE-43]
	_ = x[INVALID-44]
	_ = x[END_OF_FILE-45]
}

const _TokenKind_name = "NONELEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSLASHSTARSEMICOLONCOLONQUESTIONBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERVARFUNCLASSSUPERTHISIFELSEWHILEFORORANDASSERTPRINTRETURNBREAKCONTINUENILTRUEFALSEINVALIDEND_OF_FILE"

var _TokenKind_index = [...]uint16{0, 4, 14, 25, 35, 46, 51, 54, 59, 63, 68, 72, 81, 86, 94, 98, 108, 113, 124, 131, 144, 148, 158, 168, 174, 180, 183, 186, 191, 196, 200, 202, 206, 211, 214, 216, 219, 225, 230, 236, 241, 249, 252, 256, 261, 268, 279}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
