package token

import "tree_lox/value"

type Token struct {
	Lexeme  string
	Kind    TokenKind
	Line    int
	Literal value.Value
}

//go:generate stringer -type=TokenKind
type TokenKind int16

const (
	// This never matches any token generated by the scanner.
	NONE TokenKind = iota

	// Single character tokens
	LEFT_PAREN
	RIGHT_PAREN
	LEFT_BRACE
	RIGHT_BRACE
	COMMA
	DOT
	MINUS
	PLUS
	SLASH
	STAR
	SEMICOLON
	COLON
	QUESTION

	// One or two character tokens
	BANG
	BANG_EQUAL
	EQUAL
	EQUAL_EQUAL
	GREATER
	GREATER_EQUAL
	LESS
	LESS_EQUAL

	// Literals
	IDENTIFIER
	STRING
	NUMBER

	// Keywords
	VAR
	FUN
	CLASS
	SUPER
	THIS
	IF
	ELSE
	WHILE
	FOR
	OR
	AND
	ASSERT
	PRINT
	RETURN
	BREAK
	CONTINUE
	NIL
	TRUE
	FALSE

	INVALID
	END_OF_FILE
)
